### ISSUE TITLE
I have the following problems when running the t2d_m2m_target_producers.R file:

### ISSUE THREAD

**Issue by ChenCongZ** [AuReMe/metage2metabo#34] opened 2022-02-19 08:02 UTC
> target_producers$sample <- droplevels(target_producers$sample)
Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character" @cfrioux

**Comment by cfrioux** [comment] 2022-02-21 07:27
I cannot reproduce the error with any combination of the options. 
The error states that you are trying to change the factor levels for a variable that is not a factor but characters.

Did you modify the script before running it?

**Comment by cfrioux** [comment] 2022-03-16 15:49
SBML object identifiers cannot hold non alphanumeric characters (i.e. only [A-Za-z0-9_] are allowed).
Hence other characters have to be encoded to be suitable as IDs. `-` is encoded as `__45__`. 

The underlying libraries in M2M read SBML files as XML so it is likely nothing will fail if your IDs are incorrect, but I strongly encourage you to avoid using forbidden characters in your identifiers in case you use  at some point a tool that uses libSBML.

**Comment by ChenCongZ** [comment] 2022-03-17 14:23
> SBML object identifiers cannot hold non alphanumeric characters (i.e. only [A-Za-z0-9_] are allowed). Hence other characters have to be encoded to be suitable as IDs. `-` is encoded as `__45__`.
> 
> The underlying libraries in M2M read SBML files as XML so it is likely nothing will fail if your IDs are incorrect, but I strongly encourage you to avoid using forbidden characters in your identifiers in case you use at some point a tool that uses libSBML.

Thank you very much， I see. I have encountered a problem, how to convert the reaction in excle table into xml format?
Excel is this format.
G1P[c] + H2O[c] -> GLC[c] + PI[c]
H2O[c] + SALCN6P[c] -> G6P[c] + SALAL[c]
H2O[c] + ARBT6P[c] -> BENDL[c] + G6P[c]
G6P[c] <=> G1P[c]
G6P[c] <=> F6P[c]
F6P[c] + PPI[c] <=> FDP[c] + PI[c] + H[c]
ATP[c] + GLC[c] -> ADP[c] + G6P[c] + H[c]
ATP[c] + F6P[c] -> ADP[c] + FDP[c] + H[c]
FDP[c] + H2O[c] -> F6P[c] + PI[c] 
FDP[c] <=> T3P2[c] + T3P1[c]

**Comment by cfrioux** [comment] 2022-03-17 17:46
I do not work with Excel files but you might want to take a look at [LibSBML](https://sbml.org/software/libsbml/5.18.0/docs/formatted/python-api/libsbml-api-guide.html) or [Cobrapy](https://cobrapy.readthedocs.io/en/latest/).

You just reopened the issue but there are no problems related to metage2metabo here so I'll close it.

**Closed by cfrioux** 2022-03-17 17:46 UTC

**Comment by ChenCongZ** [comment] 2022-03-19 09:35
> I do not work with Excel files but you might want to take a look at [LibSBML](https://sbml.org/software/libsbml/5.18.0/docs/formatted/python-api/libsbml-api-guide.html) or [Cobrapy](https://cobrapy.readthedocs.io/en/latest/).
> 
> You just reopened the issue but there are no problems related to metage2metabo here so I'll close it.

Thank you very much. What I want to ask is how to automatically generate sbml from data instead of editing it one by one. Popularly speaking, it is to convert xlsx format into sbml format.

**Comment by ChenCongZ** [comment] 2022-03-19 12:57
> > I do not work with Excel files but you might want to take a look at [LibSBML](https://sbml.org/software/libsbml/5.18.0/docs/formatted/python-api/libsbml-api-guide.html) or [Cobrapy](https://cobrapy.readthedocs.io/en/latest/).
> > You just reopened the issue but there are no problems related to metage2metabo here so I'll close it.
> 
> Thank you very much. What I want to ask is how to automatically generate sbml from data instead of editing it one by one. Popularly speaking, it is to convert xlsx format into sbml format.

Do we need to edit each metabolite and reaction? Do you process data like this? The workload will probably become very large!
